### PR TITLE
Don't try to do stuff after transition if the component is destroying or destroyed

### LINKED ISSUE #34: Acceptance test throws error from `liquid-destination.js`
I've built a modal with `liquid-wormhole`, everything works good on the app side but when I ran some acceptance tests related to the modal, I received error thrown from `liquid-destination.js` pointing to [this line](https://github.com/pzuraq/liquid-wormhole/blob/master/addon/components/liquid-destination.js#L116), which is inside `afterTransition` action.
screen shot 2017-06-15 at 11 21 40 pm

screen shot 2017-06-15 at 11 21 52 pm

The modal component is rendered under a parent route, and the acceptance tests are just verifying open modal and close modal are going to the correct route.

If I set `debugger` around the `this.$(view.element).find('.liquid-wormhole-element').css({ visibility: 'visible' });` I can see sometimes `this.$(view.element)` is undefined. I haven't figured how that happened, but seems simply adding a conditional check `if (this.$(view.element)) {}` is able to fix the issue.

Please help me look into this. Thanks :-)

### PR DESCRIPTION
**Pull request by alexspeller**
Fixes #34

### CODE REVIEW

**Comment by pzuraq** [comment]
Thanks for the fix! 😄

Failure looks like it's only on beta, likely unrelated to this change. Going to merge and open up a separate issue for thar.

**Comment by pzuraq** [comment]
Patch version published

**Comment by billdami** [comment]
@alexspeller @pzuraq any chance you can cut a new release with this fix? I'm seeing the same errors as #34 in my integration tests for components that extend ember-modal-dialog

**Comment by pzuraq** [comment]
This was released in v2.0.6, can you conifrm the version of liquid-wormhole?

**Comment by billdami** [comment]
@pzuraq ah my mistake! I was looking at https://github.com/pzuraq/liquid-wormhole/releases and for some reason it lists 2.0.5 as the latest release (which is what I was on). But the npmjs.com package page does correct list the latest version :)

**Pull request merged**
