### PR TITLE
Make liquid-destination removable

### PR DESCRIPTION
**Pull request by Cryrivers**
To solve issue #30

### CODE REVIEW

**Comment by pzuraq** [comment]
👍  Good catch, I haven't actually used many `liquid-destination`s besides the default one. Will merge once tests pass!

**Comment by Cryrivers** [comment]
Could you cut a release?

**Comment by pzuraq** [comment]
First thing in the mornin

**Comment by Cryrivers** [comment]
great, thank you!

**Comment by pzuraq** [comment]
release cut

**Pull request merged**
